version: "3.7"

services:
  n8n:
    build: .
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      - WEBHOOK_URL=http://localhost:5678/

    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./docubot:/opt/projetos/docubot
      - ./faiss_index:/data/faiss_index
